"""
Pulls a small, fresh batch of learning resources from free, keyless
sources and writes them to frontend/data/resources.json.

Run it yourself:
    pip install requests feedparser
    python scripts/refresh_resources.py

Or let GitHub Actions run it on a schedule for free — see
.github/workflows/refresh-resources.yml. Either way, this script is
the ONLY thing that writes resources.json. The frontend only reads
it (see frontend/js/resources.js). Keeping "who writes" and "who
reads" in separate files is what makes the scheduled-job pattern
work without the frontend needing to know anything changed.

Sources used (all free, no API key required):
  - Hacker News (via the Algolia HN Search API)
  - arXiv (recent AI/ML papers)
  - RSS feeds (Real Python, python.org blog)
"""

import datetime
import json
from pathlib import Path

import feedparser
import requests

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "frontend" / "data" / "resources.json"

HN_TOPICS = ["python", "machine learning", "cybersecurity"]
RSS_FEEDS = [
    ("Real Python", "https://realpython.com/atom.xml"),
    ("Python Insider", "https://blog.python.org/feeds/posts/default"),
]
ARXIV_QUERY = "cat:cs.LG"  # machine learning category


def fetch_hn(topic: str, limit: int = 3) -> list[dict]:
    resp = requests.get(
        "https://hn.algolia.com/api/v1/search",
        params={"query": topic, "tags": "story", "hitsPerPage": limit},
        timeout=10,
    )
    resp.raise_for_status()
    hits = resp.json().get("hits", [])
    return [
        {"title": h["title"], "url": h.get("url") or f"https://news.ycombinator.com/item?id={h['objectID']}",
         "source": "Hacker News", "tag": topic}
        for h in hits if h.get("title")
    ]


def fetch_rss(name: str, url: str, limit: int = 3) -> list[dict]:
    parsed = feedparser.parse(url)
    return [
        {"title": entry.title, "url": entry.link, "source": name, "tag": "blog"}
        for entry in parsed.entries[:limit]
    ]


def fetch_arxiv(limit: int = 3) -> list[dict]:
    resp = requests.get(
        "http://export.arxiv.org/api/query",
        params={"search_query": ARXIV_QUERY, "sortBy": "submittedDate", "sortOrder": "descending", "max_results": limit},
        timeout=10,
    )
    resp.raise_for_status()
    parsed = feedparser.parse(resp.text)
    return [
        {"title": entry.title.replace("\n", " ").strip(), "url": entry.link, "source": "arXiv", "tag": "paper"}
        for entry in parsed.entries
    ]


def main():
    items = []
    for topic in HN_TOPICS:
        items += fetch_hn(topic)
    for name, url in RSS_FEEDS:
        items += fetch_rss(name, url)
    items += fetch_arxiv()

    output = {
        "last_refreshed": datetime.datetime.utcnow().isoformat() + "Z",
        "note": "Auto-generated by scripts/refresh_resources.py — do not edit by hand.",
        "items": items,
    }
    OUTPUT_PATH.write_text(json.dumps(output, indent=2))
    print(f"Wrote {len(items)} resources to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
